import type * as monaco from 'monaco-editor';

type Monaco = typeof monaco;

// Custom themes used by the notebook SQL cells. Defined once at bootstrap
// — Monaco's theme registry is global so per-cell registration was
// redundant.
const defineSqlEnhancedThemes = (monacoNs: Monaco): void => {
  monacoNs.editor.defineTheme('sql-enhanced-dark', {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'keyword.sql', foreground: '569CD6', fontStyle: 'bold' },
      { token: 'identifier.table', foreground: '4EC9B0' },
      { token: 'identifier.column', foreground: '9CDCFE' },
      { token: 'predefined.sql', foreground: 'DCDCAA' },
      { token: 'string.sql', foreground: 'CE9178' },
      { token: 'number.sql', foreground: 'B5CEA8' },
      { token: 'comment.sql', foreground: '6A9955', fontStyle: 'italic' },
      { token: 'operator.sql', foreground: 'D4D4D4' },
      { token: 'type.sql', foreground: '4EC9B0' },
    ],
    colors: {
      'editor.background': '#121212',
      'editor.foreground': '#D4D4D4',
      'editor.lineHighlightBackground': '#1e1e1e',
      'editorCursor.foreground': '#AEAFAD',
      'editor.selectionBackground': '#264F78',
      'editor.inactiveSelectionBackground': '#3A3D41',
    },
  });

  monacoNs.editor.defineTheme('sql-enhanced-light', {
    base: 'vs',
    inherit: true,
    rules: [
      { token: 'keyword.sql', foreground: '0000FF', fontStyle: 'bold' },
      { token: 'identifier.table', foreground: '267F99' },
      { token: 'identifier.column', foreground: '001080' },
      { token: 'predefined.sql', foreground: '795E26' },
      { token: 'string.sql', foreground: 'A31515' },
      { token: 'number.sql', foreground: '098658' },
      { token: 'comment.sql', foreground: '008000', fontStyle: 'italic' },
      { token: 'operator.sql', foreground: '000000' },
      { token: 'type.sql', foreground: '267F99' },
    ],
    colors: {
      'editor.background': '#fafafa',
      'editor.foreground': '#000000',
      'editor.lineHighlightBackground': '#f5f5f5',
      'editorCursor.foreground': '#000000',
      'editor.selectionBackground': '#ADD6FF',
      'editor.inactiveSelectionBackground': '#E5EBF1',
    },
  });
};

// Replace Monaco's default 'sql' Monarch tokenizer with one that splits
// keywords / functions / types / identifiers into more granular tokens, so
// the enhanced themes above can colour them distinctly.
const defineSqlEnhancedTokens = (monacoNs: Monaco): void => {
  monacoNs.languages.setMonarchTokensProvider('sql', {
    defaultToken: '',
    tokenPostfix: '.sql',
    ignoreCase: true,

    keywords: [
      'SELECT',
      'FROM',
      'WHERE',
      'JOIN',
      'LEFT',
      'RIGHT',
      'INNER',
      'OUTER',
      'FULL',
      'CROSS',
      'ON',
      'AS',
      'AND',
      'OR',
      'NOT',
      'IN',
      'EXISTS',
      'BETWEEN',
      'LIKE',
      'ILIKE',
      'IS',
      'NULL',
      'TRUE',
      'FALSE',
      'GROUP',
      'BY',
      'HAVING',
      'ORDER',
      'ASC',
      'DESC',
      'LIMIT',
      'OFFSET',
      'UNION',
      'INTERSECT',
      'EXCEPT',
      'ALL',
      'DISTINCT',
      'CASE',
      'WHEN',
      'THEN',
      'ELSE',
      'END',
      'WITH',
      'RECURSIVE',
      'OVER',
      'PARTITION',
      'WINDOW',
      'ROWS',
      'RANGE',
      'UNBOUNDED',
      'PRECEDING',
      'FOLLOWING',
      'CURRENT',
      'ROW',
      'INSERT',
      'INTO',
      'VALUES',
      'UPDATE',
      'SET',
      'DELETE',
      'CREATE',
      'DROP',
      'ALTER',
      'TABLE',
      'VIEW',
      'INDEX',
      'SCHEMA',
      'DATABASE',
      'CONSTRAINT',
      'PRIMARY',
      'KEY',
      'FOREIGN',
      'REFERENCES',
      'UNIQUE',
      'CHECK',
      'DEFAULT',
      'USING',
      'SAMPLE',
      'QUALIFY',
      'EXCLUDE',
      'REPLACE',
    ],

    operators: [
      '=',
      '>',
      '<',
      '!',
      '~',
      '?',
      ':',
      '==',
      '<=',
      '>=',
      '!=',
      '<>',
      '&&',
      '||',
      '++',
      '--',
      '+',
      '-',
      '*',
      '/',
      '&',
      '|',
      '^',
      '%',
      '<<',
      '>>',
      '>>>',
      '+=',
      '-=',
      '*=',
      '/=',
      '&=',
      '|=',
      '^=',
      '%=',
      '<<=',
      '>>=',
      '>>>=',
    ],

    builtinFunctions: [
      'COUNT',
      'SUM',
      'AVG',
      'MIN',
      'MAX',
      'STDDEV',
      'VARIANCE',
      'STRING_AGG',
      'ARRAY_AGG',
      'LIST',
      'MEDIAN',
      'MODE',
      'ROW_NUMBER',
      'RANK',
      'DENSE_RANK',
      'PERCENT_RANK',
      'CUME_DIST',
      'NTILE',
      'LAG',
      'LEAD',
      'FIRST_VALUE',
      'LAST_VALUE',
      'NTH_VALUE',
      'CONCAT',
      'SUBSTRING',
      'LENGTH',
      'UPPER',
      'LOWER',
      'TRIM',
      'LTRIM',
      'RTRIM',
      'REPLACE',
      'SPLIT',
      'REGEXP_MATCHES',
      'REGEXP_REPLACE',
      'NOW',
      'CURRENT_DATE',
      'CURRENT_TIME',
      'CURRENT_TIMESTAMP',
      'DATE_TRUNC',
      'DATE_PART',
      'EXTRACT',
      'AGE',
      'INTERVAL',
      'CAST',
      'TRY_CAST',
      'COALESCE',
      'NULLIF',
      'IFNULL',
      'ABS',
      'CEIL',
      'FLOOR',
      'ROUND',
      'SQRT',
      'POWER',
      'EXP',
      'LN',
      'LOG',
      'IF',
      'CASE',
      'WHEN',
      'THEN',
      'ELSE',
      'END',
    ],

    builtinTypes: [
      'INTEGER',
      'BIGINT',
      'SMALLINT',
      'TINYINT',
      'DOUBLE',
      'FLOAT',
      'DECIMAL',
      'NUMERIC',
      'VARCHAR',
      'CHAR',
      'TEXT',
      'STRING',
      'BOOLEAN',
      'BOOL',
      'DATE',
      'TIME',
      'TIMESTAMP',
      'TIMESTAMPTZ',
      'INTERVAL',
      'JSON',
      'JSONB',
      'UUID',
      'BLOB',
      'BYTEA',
    ],

    tokenizer: {
      root: [
        { include: '@whitespace' },
        [/'/, 'string.sql', '@string'],
        [/"/, 'identifier.quoted.sql', '@quotedIdentifier'],
        [/\d+(\.\d+)?/, 'number.sql'],
        [
          /[a-zA-Z_]\w*/,
          {
            cases: {
              '@keywords': 'keyword.sql',
              '@builtinFunctions': 'predefined.sql',
              '@builtinTypes': 'type.sql',
              '@default': 'identifier.sql',
            },
          },
        ],
        [/[;,.]/, 'delimiter.sql'],
        [/[()[\]]/, 'delimiter.parenthesis.sql'],
        [/[<>]=?/, 'operator.sql'],
        [/[+\-*/%]/, 'operator.sql'],
        [/[=!<>]=/, 'operator.sql'],
      ],
      whitespace: [
        [/\s+/, 'white'],
        [/--.*$/, 'comment.sql'],
        [/\/\*/, 'comment.sql', '@comment'],
      ],
      comment: [
        [/[^/*]+/, 'comment.sql'],
        [/\*\//, 'comment.sql', '@pop'],
        [/[/*]/, 'comment.sql'],
      ],
      string: [
        [/[^\\']+/, 'string.sql'],
        [/\\./, 'string.escape.sql'],
        [/'/, 'string.sql', '@pop'],
      ],
      quotedIdentifier: [
        [/[^\\"]+/, 'identifier.quoted.sql'],
        [/\\./, 'string.escape.sql'],
        [/"/, 'identifier.quoted.sql', '@pop'],
      ],
    },
  });
};

let registered = false;

/**
 * Register the `sql-enhanced-dark` / `sql-enhanced-light` themes and the
 * granular `sql` Monarch tokenizer used by the notebook SQL cells.
 * Idempotent.
 */
export const registerSqlEnhanced = (monacoNs: Monaco): void => {
  if (registered) return;
  registered = true;
  defineSqlEnhancedThemes(monacoNs);
  defineSqlEnhancedTokens(monacoNs);
};
