export const DUCKLAKE_SUPPORTED_COLUMN_TYPES = [
  'boolean',
  'int8',
  'int16',
  'int32',
  'int64',
  'uint8',
  'uint16',
  'uint32',
  'uint64',
  'float32',
  'float64',
  'decimal(18,3)',
  'time',
  'timetz',
  'date',
  'timestamp',
  'timestamptz',
  'timestamp_s',
  'timestamp_ms',
  'timestamp_ns',
  'interval',
  'varchar',
  'blob',
  'json',
  'uuid',
  'list(INTEGER)',
  'struct(name VARCHAR)',
  'map(VARCHAR, INTEGER)',
];
